services:
  elasticsearch:
    image: elasticsearch:8.14.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  astro:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 4321:4321
    depends_on:
      - elasticsearch
