services:
  elasticsearch:
    image: elasticsearch:8.14.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    ports:
      - 5601:5601
    networks:
      - elastic

  astro:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 4321:4321
    depends_on:
      - elasticsearch
    networks:
      - elastic
      
networks:
  elastic: